// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3jbBsTsAVZv4BqgIPXg17_3imOgZ4qbs',
    appId: '1:347373334103:web:6f3df76b9da053ad9dbd12',
    messagingSenderId: '347373334103',
    projectId: 'kenorider-420a2',
    authDomain: 'kenorider-420a2.firebaseapp.com',
    storageBucket: 'kenorider-420a2.appspot.com',
    measurementId: 'G-QVYZBNJNSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA058qJVV7V1-b5P-VzKVD61rFMhXcoMhs',
    appId: '1:347373334103:android:0e8fabbe8fee2a2b9dbd12',
    messagingSenderId: '347373334103',
    projectId: 'kenorider-420a2',
    storageBucket: 'kenorider-420a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAC1EOIrTF9yjhBl5Db9W4zMk94_5sSu8',
    appId: '1:347373334103:ios:23ffd3068b552b0b9dbd12',
    messagingSenderId: '347373334103',
    projectId: 'kenorider-420a2',
    storageBucket: 'kenorider-420a2.appspot.com',
    iosBundleId: 'com.example.kenoriderDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAC1EOIrTF9yjhBl5Db9W4zMk94_5sSu8',
    appId: '1:347373334103:ios:23ffd3068b552b0b9dbd12',
    messagingSenderId: '347373334103',
    projectId: 'kenorider-420a2',
    storageBucket: 'kenorider-420a2.appspot.com',
    iosBundleId: 'com.example.kenoriderDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3jbBsTsAVZv4BqgIPXg17_3imOgZ4qbs',
    appId: '1:347373334103:web:291933bcfd8278199dbd12',
    messagingSenderId: '347373334103',
    projectId: 'kenorider-420a2',
    authDomain: 'kenorider-420a2.firebaseapp.com',
    storageBucket: 'kenorider-420a2.appspot.com',
    measurementId: 'G-7BBT0D48VC',
  );
}
